name: Python CI

on:
  push:

jobs:
  ci:
    uses: RWTH-EBC/ci_templates/.github/workflows/ci_pipeline.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      PYTHON_VERSION: "3.11"
      PYTHON_TEST_MATRIX: '["3.10", "3.11", "3.12", "3.13"]'
      PYTHON_PACKAGE_NAME: "agentlib_flexquant"
      USE_PYLINT: true
      USE_RUFF: true
      BUILD_PACKAGE: true
      GENERATE_DOCUMENTATION: true
      GH_PAGES: true
      CREATE_PAGES_ON_FAILURE: true
      EXECUTE_TESTS: true
      EXECUTE_COVERAGE_TEST: true
